### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by ranjanan** [JuliaWeb/HttpParser.jl#57]
Master seems to be free of build dep warns. A new tagged version would make  the`Pkg.add` a lot better.

**Comment by ranjanan** [comment]
I guess we can tag after #58

**Comment by ranjanan** [comment]
Actually, we should wait. It's broken on Windows (#59 and https://github.com/JuliaLang/METADATA.jl/pull/5278)

**Comment by ranjanan** [comment]
Now that it works on Windows (#60 and eb19d5fc4100dfb38cac64efa0ee4ed5ed3c7bb2), we've sent out a PR on METADATA (https://github.com/JuliaLang/METADATA.jl/pull/5989)

**Comment by tkelman** [comment]
This needs to do verification of any existing binaries it may find. And please put the old binaries back where they were, use versioned downloads - with actual BinDeps verification that the binaries are new enough, otherwise anyone who has the package installed is going to try to reuse the already-downloaded old binaries and it isn't going to work.

**Comment by ranjanan** [comment]
Can I add a check to the build.jl file that downloads a binary depending on the package version installed (For example, ` if Pkg.installed() > v"0.1.1"`, download this, otherwise download that.)

**Comment by tkelman** [comment]
`Pkg.installed` is very slow, don't use it. What matters is that the binary has the right library version that the ccall bindings were written against.
