### ISSUE TITLE
Error Building HttpParser on 1.0.0

### ISSUE THREAD

**Issue by mgiugliano** [JuliaWeb/HttpParser.jl#89]
Building HttpParser → `~/.julia/packages/HttpParser/yGK3a/deps/build.log`
┌ Error: Error building `HttpParser`:
│ ERROR: LoadError: UndefVarError: is_windows not defined
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] include at ./boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1038
│  [4] include(::Module, ::String) at ./sysimg.jl:29
│  [5] include(::String) at ./client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at /Users/XXX/.julia/packages/HttpParser/yGK3a/deps/build.jl:10
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

**Comment by piovac** [comment]
The problem is that the build bile is using `is_windows()` and `is_unix()` which have been deprecated for a while. I was able to make it work with a quick fix. Edit the build file /Users/XXX/.julia/packages/HttpParser/yGK3a/deps/build.jl and change those two functions with `Sys.iswindows()` and `Sys.isunix()`

**Comment by Navrique** [comment]
@piovac 
Thank you

**Comment by JaapHaitsma** [comment]
Would be great if the maintainer of this package could make the changes proposed by @piovac
